// Copy the static RPC fallback this SDK reads (every chain the coordination layer reads) out of the RPC registry
// (packages/rpc/fallback.json) into src/rpc-fallback.ts. @taifoon/jev ships no runtime dependency, so the list is vendored;
// warmbed (https://warmbed.taifoon.dev) is always asked first, this list is used only when warmbed does not answer.
// Loopback endpoints (the box's own nodes) are left out: a published package never runs on the box.
//   node scripts/vendor-rpc.mjs            write src/rpc-fallback.ts
//   node scripts/vendor-rpc.mjs --check    exit 1 on drift (skipped where the registry is absent)
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
export const OUT = join(root, 'src', 'rpc-fallback.ts');
export const REGISTRY = process.env.RPC_REGISTRY ?? join(root, '..', '..', 'packages', 'rpc', 'fallback.json');
// every chain the coordination layer reads (verify() reads the ones that carry Jev logs)
export const CHAINS = [36927, 8453, 42161, 5042, 4663, 143, 3692781, 1];
export const found = () => existsSync(REGISTRY);

export function render(doc) {
  const rows = CHAINS.map((c) => {
    const eps = (doc.chains[String(c)]?.endpoints ?? []).filter((e) => !/^https?:\/\/(127\.0\.0\.1|localhost)/.test(e.url));
    const logs = eps.filter((e) => e.span >= 500).sort((a, b) => b.span - a.span).map((e) => e.url);
    const call = eps.map((e) => e.url);
    return `  ${c}: {\n    logs: ${JSON.stringify(logs)},\n    call: ${JSON.stringify(call)},\n  },`;
  });
  return `// GENERATED by scripts/vendor-rpc.mjs from packages/rpc/fallback.json (measured ${doc.measured}). Do not edit.\n`
    + `// The fallback only: verify() asks warmbed's rotation first and uses these when warmbed does not answer.\n`
    + `export const RPC_FALLBACK: Readonly<Record<number, { logs: readonly string[]; call: readonly string[] }>> = {\n${rows.join('\n')}\n};\n`;
}

if (process.argv[1] && import.meta.url.endsWith(process.argv[1].split('/').pop())) {
  if (!found()) { console.log(`registry absent (${REGISTRY}): skipped`); process.exit(0); }
  const want = render(JSON.parse(readFileSync(REGISTRY, 'utf8')));
  if (process.argv.includes('--check')) {
    if (!existsSync(OUT) || readFileSync(OUT, 'utf8') !== want) { console.error('src/rpc-fallback.ts differs from the RPC registry: run node scripts/vendor-rpc.mjs'); process.exit(1); }
    console.log('src/rpc-fallback.ts equals the RPC registry');
  } else { writeFileSync(OUT, want); console.log('wrote', OUT); }
}
