// GENERATED by scripts/vendor-rpc.mjs from packages/rpc/fallback.json (measured 2026-10-08). Do not edit.
// The fallback only: verify() asks warmbed's rotation first and uses these when warmbed does not answer.
export const RPC_FALLBACK: Readonly<Record<number, { logs: readonly string[]; call: readonly string[] }>> = {
  36927: {
    logs: ["https://rpc.taifoon.dev"],
    call: ["https://rpc.taifoon.dev"],
  },
  8453: {
    logs: ["https://base.rpc.blxrbdn.com","https://base.public.blockpi.network/v1/rpc/public","https://base-rpc.publicnode.com","https://gateway.tenderly.co/public/base","https://base.gateway.tenderly.co"],
    call: ["https://base.rpc.blxrbdn.com","https://base.public.blockpi.network/v1/rpc/public","https://gateway.tenderly.co/public/base","https://base.gateway.tenderly.co","https://base-rpc.publicnode.com","https://developer-access-mainnet.base.org","https://mainnet.base.org","https://base.drpc.org","https://base-mainnet.public.blastapi.io","https://api.zan.top/base-mainnet","https://base.meowrpc.com","https://base-public.nodies.app"],
  },
  42161: {
    logs: ["https://arb1.arbitrum.io/rpc","https://gateway.tenderly.co/public/arbitrum","https://arbitrum.gateway.tenderly.co"],
    call: ["https://arb1.arbitrum.io/rpc","https://gateway.tenderly.co/public/arbitrum","https://arbitrum.gateway.tenderly.co","https://arbitrum.drpc.org","https://arbitrum-one-rpc.publicnode.com","https://arbitrum-one.public.blastapi.io"],
  },
  5042: {
    logs: ["https://rpc.mainnet.arc.io","https://rpc.quicknode.mainnet.arc.io","https://rpc.blockdaemon.mainnet.arc.io","https://arc.gateway.tenderly.co"],
    call: ["https://rpc.mainnet.arc.io","https://rpc.quicknode.mainnet.arc.io","https://rpc.blockdaemon.mainnet.arc.io","https://arc.gateway.tenderly.co","https://rpc.drpc.mainnet.arc.io","https://arc.drpc.org","https://arc-rpc.publicnode.com"],
  },
  4663: {
    logs: ["https://rpc.mainnet.chain.robinhood.com","https://rpc.ordofi.network"],
    call: ["https://rpc.mainnet.chain.robinhood.com","https://rpc.ordofi.network","https://robinhood.drpc.org","https://robinhood-rpc.publicnode.com"],
  },
  143: {
    logs: ["https://rpc1.monad.xyz","https://infra.originstake.com/monad/evm"],
    call: ["https://rpc1.monad.xyz","https://infra.originstake.com/monad/evm","https://rpc.monad.xyz","https://rpc3.monad.xyz","https://rpc-mainnet.monadinfra.com","https://monad.gateway.tenderly.co","https://rpc.ankr.com/monad_mainnet","https://rpc4.monad.xyz"],
  },
  3692781: {
    logs: ["https://mainnet.taifoon.dev"],
    call: ["https://mainnet.taifoon.dev"],
  },
  1: {
    logs: ["https://gateway.tenderly.co/public/mainnet","https://rpc.mevblocker.io","https://mainnet.gateway.tenderly.co","https://ethereum.publicnode.com","https://rpc.flashbots.net"],
    call: ["https://gateway.tenderly.co/public/mainnet","https://mainnet.gateway.tenderly.co","https://rpc.mevblocker.io","https://ethereum-rpc.publicnode.com","https://ethereum.publicnode.com","https://rpc.flashbots.net","https://eth.drpc.org"],
  },
};
